import type { Metadata } from 'next';

import { pretendard } from '@/assets/fonts';
import { cn } from '@/lib/cn';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(pretendard.variable, 'font-pretendard antialiased')}>
        {children}
      </body>
    </html>
  );
}
